SEOMonitor.WebMember/Controllers/HomeController.cs
using CsvHelper;
using CsvHelper.Configuration;
using Inhouse.Sdk.Logger;
using SEOMonitor.Model.Database.Monitor;
using SEOMonitor.Model.Database.Transaction;
using SEOMonitor.WebMember.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using SEOMonitor.Business;
using SEOMonitor.Repository;

namespace SEOMonitor.WebMember.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {

        private static string UrlGoogle = "https://www.google.com.mx/search?sclient=psy-ab&site=&source=hp&q={0}";
        private TextWriter textWriter;
        private GoogleResultBusiness googleResultBusiness = new GoogleResultBusiness(new CGoogleResultRepository());
        private GoogleTransactionBusiness googleTransactionBusiness = new GoogleTransactionBusiness(new CGoogleTransactionRepository());

        // GET: Home
        public ActionResult Index()
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            if (currentUser == null)
            {
                return RedirectToAction("LogOut", "Account");
            }
            List<GoogleResultsMonitorModel> list = googleResultBusiness.GetByOwner(currentUser.Id);
            //GoogleResultsMonitor.Get(currentUser.Id).OrderBy(m => m.Name).ToList();

            //List<GoogleMonitorTransaction> toedit = GoogleMonitorTransaction.Get();
            //foreach(var tr in toedit)
            //{
            //    var tuple = Core.Utils.GetNumberOfResultsAndTime(tr.FormattedResult);
            //    tr.NumberOfResults = tuple.Item1;
            //    tr.TimeSearch = tuple.Item2;
            //    tr.Update();
            //}

            return View(list);
        }

        public ActionResult Create()
        {
            RegisterMonitorModel model = new RegisterMonitorModel();
            model.Active = true;
            model.SendEmail = true;
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(RegisterMonitorModel model)
        {
            ModelState.Remove("Id");
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var currentUser = BaseController.GetCurrentUser(Request);

            GoogleResultsMonitorModel monitor = new GoogleResultsMonitorModel(model.Name,
                model.Query, 
                string.Format(UrlGoogle, Server.HtmlEncode(model.Query)),
                model.Comments,
                currentUser.Id,
                model.Active,
                model.SendEmail
                );

            //monitor.Save();
            googleResultBusiness.Save(monitor);

            if(monitor.Id > 0)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Edit(int Id)
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            //GoogleResultsMonitor model = GoogleResultsMonitor.Get(Id, currentUser.Id);
            GoogleResultsMonitorModel model = googleResultBusiness.GetByOwner(Id, currentUser.Id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }
            
            return View(new RegisterMonitorModel(model.Id, model.Name, model.Query, model.Comments, model.Url, model.Active, model.SendEmail));
        }

        [HttpPost]
        public ActionResult Edit(RegisterMonitorModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var currentUser = BaseController.GetCurrentUser(Request);


            GoogleResultsMonitorModel editModel = new GoogleResultsMonitorModel(model.Id, model.Name, model.Query,
                string.Format(UrlGoogle, Server.HtmlEncode(model.Query)), model.Comments, currentUser.Id, model.Active, model.SendEmail);

            googleResultBusiness.Update(editModel);

            return RedirectToAction("Index");
        }

        public ActionResult Details(int Id)
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            //GoogleResultsMonitor model = GoogleResultsMonitor.Get(Id, currentUser.Id);
            GoogleResultsMonitorModel model = googleResultBusiness.GetByOwner(Id, currentUser.Id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(new RegisterMonitorModel(model.Id, model.Name, model.Query, model.Comments, model.Url, model.Active, model.SendEmail));
        }

        public ActionResult Delete(int Id)
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            //GoogleResultsMonitor model = GoogleResultsMonitor.Get(Id, currentUser.Id);
            GoogleResultsMonitorModel model = googleResultBusiness.GetByOwner(Id, currentUser.Id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            return View(new RegisterMonitorModel(model.Id, model.Name, model.Query, model.Comments, model.Url, model.Active, model.SendEmail));
        }
        
        [HttpPost]
        public ActionResult Delete(int Id, GoogleResultsMonitorModel delete)
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            GoogleResultsMonitorModel model = googleResultBusiness.GetByOwner(Id, currentUser.Id);
            if (model == null)
            {
                return RedirectToAction("Index");
            }

            googleResultBusiness.Delete(model.Id);
            return RedirectToAction("Index");
        }


        public ActionResult GetMonitorTransactions(FilterMonitorModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView(new List<GoogleMonitorTransactionModel>());
            }

            List<GoogleMonitorTransactionModel> transactions = new List<GoogleMonitorTransactionModel>();
            if (model.StartDate == null && model.EndDate == null)
            {
                var currentUser = BaseController.GetCurrentUser(Request);
                //transactions = GoogleMonitorTransaction.Get(model.IdMonitor);
                transactions = googleTransactionBusiness.GetList(model.IdMonitor);
                return PartialView(transactions);
            }

            //transactions = GoogleMonitorTransaction.Get(model.IdMonitor, model.StartDate, model.EndDate);
            transactions = googleTransactionBusiness.GetList(model.IdMonitor, model.StartDate, model.EndDate);

            return PartialView(transactions);
        }

        public ActionResult GetCSVTransactions(FilterMonitorModel model)
        {

            var currentUser = BaseController.GetCurrentUser(Request);
            GoogleResultsMonitorModel monitor = googleResultBusiness.GetByOwner(model.IdMonitor, currentUser.Id);

            List<GoogleMonitorTransactionModel> transactions = new List<GoogleMonitorTransactionModel>();
            if (model.StartDate == null && model.EndDate == null)
            {
                transactions = googleTransactionBusiness.GetList(model.IdMonitor);
            }
            else
            {
                transactions = googleTransactionBusiness.GetList(model.IdMonitor, model.StartDate, model.EndDate);
            }


            var filename = Server.MapPath("/TmpFiles/" + Guid.NewGuid().ToString().Replace("-", "") + ".csv");
            textWriter = System.IO.File.CreateText(filename);
            var csv = new CsvWriter(textWriter);


            csv.WriteField("Date");
            csv.WriteField("FormattedResult");
            csv.WriteField("Query");
            csv.WriteField("Url");
            csv.WriteField("NumberOfResults");
            csv.WriteField("TimeSearch");
            csv.NextRecord();
            foreach (var item in transactions)
            {
                csv.WriteField(item.Date.ToString());
                csv.WriteField(item.FormattedResult);
                csv.WriteField(item.Query);
                csv.WriteField(item.Url);
                csv.WriteField(item.NumberOfResults);
                csv.WriteField(item.TimeSearch);
                csv.NextRecord();
            }
            
            //csv.WriteRecords(transactions);

            textWriter.Close();
            byte[] bytes = System.IO.File.ReadAllBytes(filename);
            System.IO.File.Delete(filename);
            return File(bytes, "text/csv", monitor.Name + "_" + DateTime.Now.ToString() + ".csv");

        }
    }
}

SEOMonitor.WebMember/Controllers/crawlerController.cs
using RestSharp;
using SEMonitor.Core;
using SEOMonitor.Business;
using SEOMonitor.Model.Apifier;
using SEOMonitor.Model.Database.Monitor;
using SEOMonitor.Model.Database.Transaction;
using SEOMonitor.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SEOMonitor.WebMember.Controllers
{
    public class CrawlerController : Controller
    {
        private GoogleResultBusiness googleResultBusiness = new GoogleResultBusiness(new CGoogleResultRepository());
        private GoogleTransactionBusiness googleTransactionBusiness = new GoogleTransactionBusiness(new CGoogleTransactionRepository());
        private GoogleRelatedTermBusiness googleRelatedTermBusiness = new GoogleRelatedTermBusiness(new CGoogleRelatedTermRepository());
        public ActionResult ExecuteSearch(long MonitorId)
        {
            var currentUser = BaseController.GetCurrentUser(Request);
            GoogleResultsMonitorModel monitor = googleResultBusiness.GetByOwner(MonitorId, currentUser.Id);
            ApifierCrawler crawler = new ApifierCrawler();
            ResultsModel results = crawler.ExecuteCrawl(currentUser.Id, monitor);

            string formattedresult = "";
            if (results.pageFunctionResult != null)
            {
                long numberOfResults = 0;
                decimal timeSearch = 0;
                Tuple<long, decimal> resultsTuple = new Tuple<long, decimal>(numberOfResults, timeSearch);
                resultsTuple = Core.Utils.GetNumberOfResultsAndTime(results.pageFunctionResult.results);
                formattedresult = results.pageFunctionResult.results;
                GoogleMonitorTransactionModel transaction = new GoogleMonitorTransactionModel(
                    monitor.Id, formattedresult, monitor.Query, 
                    monitor.Url, resultsTuple.Item1, resultsTuple.Item2);
                googleTransactionBusiness.Save(transaction);
                string relatedTerms = "";
                if (results.pageFunctionResult.relatedTerms != null)
                {
                    foreach (var item in results.pageFunctionResult.relatedTerms)
                    {
                        GoogleRelatedTermModel newTerm = new GoogleRelatedTermModel();
                        newTerm.RelatedTerm = item.term;
                        newTerm.Url = item.link;
                        googleRelatedTermBusiness.Save(newTerm, transaction.Id);
                        relatedTerms += string.Format("{0},", newTerm.RelatedTerm);
                    }
                    relatedTerms = relatedTerms.Substring(0, relatedTerms.Length - 1);
                }
            }
            //return Content(new JavaScriptSerializer().Serialize(results));
            return RedirectToAction("Details", "Home", new { Id = MonitorId });
        }
    }
}

SEOMonitor.WebMember/Views/Home/Create.cshtml
@model SEOMonitor.WebMember.Models.RegisterMonitorModel

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nuevo monitor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.HiddenFor(model => model.Id)
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Query, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SendEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SendEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SendEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SendEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SEOMonitor.WebMember/Views/Home/Delete.cshtml
@model SEOMonitor.WebMember.Models.RegisterMonitorModel

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Estás seguro de eliminar?</h3>
<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Query)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Query)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Url)*@
            <a href="@Model.Url">@Model.Url</a>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Elimnar" class="btn btn-default" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

SEOMonitor.WebMember/Views/Home/Details.cshtml
@model SEOMonitor.WebMember.Models.RegisterMonitorModel
@using SEOMonitor.Model.Database.Transaction
@using SEOMonitor.Business
@using SEOMonitor.Repository 
@{
    ViewBag.Title = "Details";
    GoogleTransactionBusiness googleTransactionBusiness = new GoogleTransactionBusiness(new CGoogleTransactionRepository());
    GoogleRelatedTermBusiness googleRelatedTermBusinnes = new GoogleRelatedTermBusiness(new CGoogleRelatedTermRepository());
    //List<GoogleMonitorTransaction> transactions = GoogleMonitorTransaction.Get(Model.Id).OrderBy(m => m.Date).ToList();
    List<GoogleMonitorTransactionModel> transactions = googleTransactionBusiness.GetList(Model.Id);
}

<h2>Detalles</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Query)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Query)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.SendEmail)
        </dt>

        <dd>
            <a href="@Model.Url">@Model.Url</a>
            @*@Html.DisplayFor(model => model.Url)*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver a la lista", "Index") |
    @Html.ActionLink("Realizar petición", "ExecuteSearch", "Crawler", new { MonitorId = Model.Id }, new { }) |
    @*@Html.ActionLink("Descargar CSV", "GetCSVTransactions","Home", new { IdMonitor = Model.Id }, new { })*@
</p>
<p><strong>Filtrar por fechas</strong></p>
<div>
    @using (Ajax.BeginForm("GetMonitorTransactions", "Home",
        new AjaxOptions {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "GET",
            OnFailure = "searchFailed",
            LoadingElementId = "ajax-loader",
            UpdateTargetId = "transactions"
        }, new { @class = "form-inline", id = "filter-trasanctions"}))
    {
        <input type="hidden" name="IdMonitor" value="@Model.Id" class="form-control" />
        <div class="input-group input-daterange">
            <input type="text" class="form-control date" name="StartDate" placeholder="Fecha inicial" style="cursor:pointer;" />
            &nbsp;
            <input type="text" class="form-control date" name="EndDate" placeholder="Fecha final" style="cursor:pointer;"/>
            <img id="ajax-loader" src="~/Content/Img/ajax-loader.gif" style="display:none;" />
            <button type="submit" class="btn btn-primary">Filtrar</button>
            <button type="button" class="btn btn-primary" onclick="fn_downloadCSV();">Descargar CSV</button>
            <button type="reset" class="btn btn-danger">Limpiar</button>
        </div>

        
    }
</div>

<h3>Historial</h3>
<div id="transactions">
    <table class="table">
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Respuesta</th>
                <th>Consulta</th>
                <th>Número de resultados</th>
                <th>Tiempo(segundos)</th>
                <th>Términos Relacionados</th>
                <th>Url</th>
            </tr>
        </thead>
        <tbody>
            @if (transactions.Count == 0)
            {
                <tr>
                    <td colspan="4">No hay monitoreos de las últimas 24 horas</td>
                </tr>
            }
            else
            {
                foreach (GoogleMonitorTransactionModel transaction in transactions)
                {
                    <tr>
                        <td>@transaction.Date</td>
                        <td>@transaction.FormattedResult</td>
                        <td>
                            <a href="@transaction.Url">@transaction.Query</a>
                        </td>
                        <td>@String.Format("{0:0,0}", transaction.NumberOfResults)</td>
                        <td>@String.Format("{0:0,0.00}", transaction.TimeSearch)</td>
                        <td>
                            @{ var listTerms = googleRelatedTermBusinnes.GetRelatedTermsByTransaction(transaction.Id); }
                            @if (listTerms.Count > 0)
                            {
                                foreach (var term in listTerms)
                                { <a href="@term.Url">@term.RelatedTerm</a><text>,</text> }
                            }
                            else
                            {
                                <text>Sin información disponible</text>
                            }
                        </td>
                        <td><a href="@transaction.Url">@transaction.Url</a></td>
                    </tr>
                }
            }
        </tbody>
    </table>

</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/bootstrap-datepicker-1.5.1/js/bootstrap-datepicker.min.js"></script>
<script src="~/Scripts/bootstrap-datepicker-1.5.1/locales/bootstrap-datepicker.es.min.js"></script>
<link href="~/Scripts/bootstrap-datepicker-1.5.1/css/bootstrap-datepicker3.min.css" rel="stylesheet"/>

@section Scripts{
    <script>
        var searchFailed = function () {
            $("#transactions").html("No se encontraron monitores en las fechas señaladas");
        }

        $("input[type = 'date']").prop('readonly', true);

        $('.input-daterange').datepicker({
            format: "yyyy/mm/dd",
            language: "es"
        });

        function fn_downloadCSV() {
            var _url = "@Url.Content("~/Home/GetCSVTransactions?")" + $("#filter-trasanctions").serialize(); //"IdMonitor=" + + "&StartDate=" + +"&EndDate=";
            window.location.href = _url;
        }
    </script>
    <style>
        .date{
            cursor:pointer;
        }
    </style>
}

SEOMonitor.WebMember/Views/Home/Edit.cshtml
@model SEOMonitor.WebMember.Models.RegisterMonitorModel

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@Model.Name</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Query, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Query, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Query, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Active, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SendEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SendEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SendEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SendEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control disabled" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })*@
                <a href="@Model.Url">@Model.Url</a>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SEOMonitor.WebMember/Views/Home/GetMonitorTransactions.cshtml
@model IEnumerable<SEOMonitor.Model.Database.Transaction.GoogleMonitorTransaction>
@using SEOMonitor.Model.Database.Monitor

<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FormattedResult)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Query)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>*@

        <th>Fecha</th>
        <th>Respuesta</th>
        <th>Consulta</th>
        <th>Número de resultados</th>
        <th>Términos relacionados</th>
        <th>Tiempo(segundos)</th>
        <th>Url</th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FormattedResult)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Query)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.NumberOfResults)*@
            @String.Format("{0:0,0}", item.NumberOfResults)
        </td>
        <td>
            @{ var listTerms = GoogleRelatedTerm.GetRelatedTermsByTransaction(item.Id); }
            @if (listTerms.Count > 0)
            {
                foreach (var term in listTerms)
                { <a href="@term.Url">@term.RelatedTerm</a> }
            }
            else
            {
                <text>Sin información disponible</text>
            }
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.TimeSearch)*@
            @String.Format("{0:0,0.00}", item.TimeSearch)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Url)*@
            <a href="@item.Url">@item.Url</a>
        </td>
    </tr>
}

</table>

SEOMonitor.WebMember/Views/Home/Index.cshtml
@model IEnumerable<SEOMonitor.Model.Database.Monitor.GoogleResultsMonitorModel>

@{
    ViewBag.Title = "Mis Monitores";
}

<h2>Mis Monitores</h2>

<p>
    @Html.ActionLink("Crear monitor", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Query)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Active)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SendEmail)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Query)
        </td>
        <td>
            @*@Html.DisplayFor(modelItem => item.Url)*@
            <a href="@item.Url">@item.Url</a>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Active)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SendEmail)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Realizar petición", "ExecuteSearch", "Crawler", new { MonitorId = item.Id }, new { })
        </td>
    </tr>
}

</table>